---
title: "Advent of Code 2021"
name: "Jeff Newmiller"
output: html_notebook
---

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(gmp)
})
rdir <- "R" # set Rmarkdown to evaluate in project directory
dtadir <- "data"
source( file.path( rdir, "adventofcode_2021.R" ) )
```


# Advent of Code 2021

## [Day 1](https://adventofcode.com/2021/day/1)

### Part 1

```{r}
dta1a <- scan("data/aoc2021_data_1a.csv")
count_increases( dta1a )
```


### Part 2

```{r}
dta1b <- rowSums( embed( dta1a, 3 ) )
count_increases(dta1b)
```

```{r}
microbenchmark::microbenchmark( ans1b1 <- dta1a
                                          |> embed( 3 )
                                          |> rowSums()
                                          |> diff()
                                          |> ( \(x) sum( 0 < x ) )()
                              , ans1b2 <- sum( diff( stats::filter( dta1a
                                                                  , rep( 1, 3 )
                                                                  , sides = 2
                                                                  )
                                                   ) > 0
                                             , na.rm = TRUE
                                             )
                              , ans1b3 <- zoo::rollsum( dta1a, 3 )
                                          |> diff()
                                          |> ( \(x) sum( 0 < x ) )()
                              , ans1b4 <- ( dta1a + lag( dta1a ) + lag( dta1a, n = 2 ) )
                                          |> na.omit()
                                          |> diff()
                                          |> ( \(x) sum( 0 < x ) )()
                              )
expect_equal( ans1b1, ans1b2 )
expect_equal( ans1b1, ans1b3 )
expect_equal( ans1b1, ans1b4 )
```

## [Day 2](https://adventofcode.com/2021/day/2)

### Part 1

```{r}
lns <- readLines( "data/aoc2021_data_2a.csv")
calc_pos_2a( lns ) |> unlist() |> prod()
```

## Part 2

```{r}
calc_pos_2b( lns ) |> unlist() |> prod()
```
## [Day 3](https://adventofcode.com/2021/day/3)

### Part 1

```{r}
lns <- scan( "data/aoc2021_data_3a.csv", what = "character", quiet = TRUE )
lv <- parse_lgl_columns( lns )
gam <- calc_gamma_rate( lv )
eps <- calc_epsilon_rate( lv )
pwr <- gam * eps
pwr
```
```{r}
m <- parse_lgl_columns_m( lns )
CO2_scrubber_rating <- calc_CO2_scrubber_rating( m )
oxy_gen_rating <- calc_oxy_gen_rating( m )
life_support_rating <- oxy_gen_rating * CO2_scrubber_rating
life_support_rating
```

## [Day 4](https://adventofcode.com/2021/day/4)

### Part 1

```{r}
lns <- readLines( "data/aoc2021_data_4a.txt" )
inp <- read_day4a( lns )
play_draws( inp$boards, inp$draws )
```

```{r}
play_draws_last( inp$boards, inp$draws )
```
## [Day 5](https://adventofcode.com/2021/day/5)

### Part 1

```{r}
lns <- readLines( "data/aoc2021_data_5a.txt" )
dta <- parse_day5a( lns )
map <- build_map_day5a( dta )
count_danger_day5a(map)
```

### Part 2

matrix is faster

```{r}
map <- build_map_day5b( dta )
count_danger_day5a(map)
```

data frame (long coordinate handling) is slower

```{r}
count_danger_day5b_df(dta)
```
## [Day 6](https://adventofcode.com/2021/day/6)

### Part 1

```{r}
lns <- readLines( "data/aoc2021_data_6a.txt" )
day0 <- parse_lanternfish( lns )
sim_days_lanternfish( day0, 80 )
```

### Part 2

```{r}
sprintf( "%20.0f", sim_days_lanternfish( day0, 256 ) )
```

## [Day 7](https://adventofcode.com/2021/day/7)

### Part 1

```{r}
dta7a <- scan( "data/aoc2021_data_7a.txt", sep = ",", quiet = TRUE)
find_min_crab_fuel( dta7a )
```


```{r}
find_min_crab_fuel( dta7a, version = 2 )
```
```{r}
microbenchmark::microbenchmark( ans7b1 <- find_min_crab_fuel( dta7a, version = 2 ) )
```

