---
title: "Advent of Code 2020"
name: "Jeff Newmiller"
output: html_notebook
---

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(gmp)
})
rdir <- "R" # set Rmarkdown to evaluate in project directory
dtadir <- "data"
source( file.path( rdir, "adventofcode_2020.R" ) )
```


# Advent of Code 2020

## [Day 1](https://adventofcode.com/2020/day/1)

### Part 1

```{r}
dta_1a <- read.csv( file.path( dtadir, "aoc2020_data_1a.csv" ), header=FALSE )[[1]]
prod( dta_1a[ find_vec_pairsum( dta_1a, 2020 ) ] )
```

### Part 2

```{r}
prod( dta_1a[ find_vec_nsum( dta_1a, 2020, 3 ) ] )
```

## [Day 2](https://adventofcode.com/2020/day/2)

### Part 1

```{r}
library(purrr)
dta_2a <- parse_pwd2a( readLines( file.path( dtadir, "aoc2020_data_2a.csv" ) ) )
sum( pmap_lgl( dta_2a, chk_pwd2a ) )
```

### Part 2

```{r}
sum( pmap_lgl( dta_2a, chk_pwd2b ) )
```

## [Day 3](https://adventofcode.com/2020/day/3)

### Part 1

```{r}
lns <- readLines( file.path( dtadir, "aoc2020_data_3a.txt" ) )
tree_map <- parse_forest( lns = lns )
count_toboggan_trees( tree_map = tree_map, row_delta = 1L, col_delta = 3L )
```

```{r}
dta_3b <- read.table( text = 
"row_delta  col_delta
         1          1
         1          3
         1          5
         1          7
         2          1
", header = TRUE )
(   dta_3b
%>% pmap_int( count_toboggan_trees, tree_map = tree_map )
%>% prod
)
```

## [Day 4](https://adventofcode.com/2020/day/4)

### Part 1

```{r}
lns <- readLines( file.path( dtadir, "aoc2020_data_4a.txt" ), warn = FALSE )
ppdb <- parse_ppdata( lns )
sum( validate_ppdata( ppdb ) )
```

```{r}
sum( validate_ppdata( ppdb, enhanced = "4b" ) )
```

## [Day 5](https://adventofcode.com/2020/day/5)

### Part 1

```{r}
s <- readLines( file.path( dtadir, "aoc2020_data_5a.txt" ), warn = FALSE )
si <- decode_bp_to_int( s )
max( si )
```

```{r}
sio <- si[ order( si ) ]
my_si <- which( 1 < diff( sio ) ) + sio[ 1 ]
my_si
#seat_id_to_row( my)
```

## [Day 6](https://adventofcode.com/2020/day/6)

### Part 1

```{r}
s <- readLines( file.path( dtadir, "aoc2020_data_6a.txt" ), warn = FALSE )
answer_list <- parse_multiline_recs( s )
sum( count_rec_answers( answer_list ) )
```

```{r}
sum( count_rec_answers( answer_list, FUN = intersect ) )
```

## [Day 7](https://adventofcode.com/2020/day/7)

### Part 1

```{r}
s <- readLines( file.path( dtadir, "aoc2020_data_7a.txt" ), warn = FALSE )
bag_rules_df <- parse_bag_rules( s )
bag_rules_mat <- make_bag_rules_matrix( bag_rules_df )
count_colors_containing( bag_rules_mat, "shiny gold" )
```

### Part 2

```{r}
count_required_bags( bag_rules_mat, "shiny gold" )
```

Also, a speed comparison: [https://gist.github.com/jdnewmil/621450c9dd7eaff8a08d84831cfd3091]

## [Day 8](https://adventofcode.com/2020/day/8)

### Part 1

```{r}
s <- readLines( file.path( dtadir, "aoc2020_data_8a.txt" ), warn = FALSE )
code <- parse_pgm_8a( s )
run_code_8a( code )
```

### Part 2

```{r}
result <- alter_nopjmps( code )
result$last_acc[ which( result$finished ) ]
```

## [Day 9](https://adventofcode.com/2020/day/9)

### Part 1

```{r}
v <- scan( file.path( dtadir, "aoc2020_data_9a.txt" ), quiet = TRUE )
v[ weak_sum <- check_sum_validity( v, 25L ) ]
```

### Part 2

```{r}
seq_ix <- find_encryption_weakness( v, weak_sum )
sum( range( v[ seq( seq_ix[ 1 ], seq_ix[ 2 ] ) ] ) ) 
```

## [Day 10](https://adventofcode.com/2020/day/10)

### Part 1

```{r}
dta_10a <- scan( file.path( dtadir, "aoc2020_data_10a.txt"), quiet = TRUE )
tbl_10a <- get_joltdiff_table( dta_10a )
tbl_10a
as.vector( tbl_10a[ "1" ] * tbl_10a[ "3" ] )
```

### Part 2

1  1
2  1
3  2
4  4
5  7
6  13
7  24

```{r}
countbin2 <- function( n ) {
  s <- sapply( seq.int( 2^n ) - 1L, dec2bin )
  l <- n-2L
  nc <- nchar( s )
  ss <- substr( s, nc - l - 1L, nc )
  length( ss[ !grepl( "111", ss ) ] )
}
```

```{r}
Reduce( function( x, y ) x * as.bigz( y )
      , count_joltdiff_combos_v( dta_10a )
      )
```

## [Day 11](https://adventofcode.com/2020/day/11)

### Part 1

```{r}
dta_11a <- readLines( file.path( dtadir, "aoc2020_data_11a.txt" ) )
seatmap <- parse_seat_map( dta_11a )
seatmap_table( seatmap_steady_state( seatmap )$seatmap )
```

### Part 2

```{r}
adjmap <- find_seatmap_visible_seats( seatmap = seatmap )
seatmap_table( seatmap_steady_state( seatmap
                                   , reseat = reseat_seatmap_11b
                                   , adjmap = adjmap
                                   )$seatmap )
```

## [Day 12](https://adventofcode.com/2020/day/12)

### Part 1

```{r}
dta_12a <- readLines( file.path( dtadir, "aoc2020_data_12a.txt" ) )
traj <- parse_traj( dta_12a )
trav_12a <- traverse_12a( traj )
get_final_manhattan( trav_12a )
```

### Part 2

```{r}
trav_12b <- traverse_12b( traj )
get_final_manhattan( trav_12b )
```

## [Day 13](https://adventofcode.com/2020/day/13)

### Part 1

```{r}
dta_13a <- readLines( file.path( dtadir, "aoc2020_data_13a.txt" ) )
sched_13a <- parse_sched_13( dta_13a )
best_13a <- find_next_bus_13a( sched_13a )
with( best_13a, id * delay )
```

### Part 2

```{r}
sched_13b <- parse_sched_13( dta_13a )
find_earliest_13b( sched_13b )
```

